//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLib.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarLib.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string FileSize_Unit_Byte {
            get {
                return ResourceManager.GetString("FileSize_Unit_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string FileSize_Unit_GB {
            get {
                return ResourceManager.GetString("FileSize_Unit_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string FileSize_Unit_KB {
            get {
                return ResourceManager.GetString("FileSize_Unit_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string FileSize_Unit_MB {
            get {
                return ResourceManager.GetString("FileSize_Unit_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string FileSize_Unit_TB {
            get {
                return ResourceManager.GetString("FileSize_Unit_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day(s).
        /// </summary>
        internal static string TimeSpan_DisplayUnit_Day {
            get {
                return ResourceManager.GetString("TimeSpan_DisplayUnit_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hour(s).
        /// </summary>
        internal static string TimeSpan_DisplayUnit_Hour {
            get {
                return ResourceManager.GetString("TimeSpan_DisplayUnit_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minute(s).
        /// </summary>
        internal static string TimeSpan_DisplayUnit_Minute {
            get {
                return ResourceManager.GetString("TimeSpan_DisplayUnit_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Second(s).
        /// </summary>
        internal static string TimeSpan_DisplayUnit_Second {
            get {
                return ResourceManager.GetString("TimeSpan_DisplayUnit_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        internal static string TimeSpan_PromptStringForMaxTimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan_PromptStringForMaxTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .
        /// </summary>
        internal static string TimeSpan_TimeEstimation_AboutPrefix {
            get {
                return ResourceManager.GetString("TimeSpan_TimeEstimation_AboutPrefix", resourceCulture);
            }
        }
    }
}
